### ISSUE TITLE
guideline configuration

### ISSUE THREAD

**Issue by tiangco** [chemodax/EditorConfigGuidelines#2]
Thanks for creating this. :)

Can the color of the guideline be configured?
Can the line type be configured? ( solid, dashed, dots?)

Thanks

**Comment by chemodax** [comment]
Color can be configured using standard Fonts and Colors Visual Studio dialog:
![image](https://user-images.githubusercontent.com/53048645/211085033-a3dc7038-0ce2-4c89-be0b-e635e41e26e3.png)

By design color cannot be set in .editorconfig, because it depends of theme and etc.

But I have added issue to specify column guideline style in .editorconfig: #3.

Does it work for you?

**Comment by tiangco** [comment]
Perfect! thanks

**Comment by chemodax** [comment]
Implemented in 1.1.0.
